package server

// TO be continure ...
const (

	// EVENT_USER_CONNECTED = iota
	EVENT_USER_CONNECTED    = "EVENT_USER_CONNECTED"
	EVENT_USER_DISCONNECTED = "EVENT_USER_DISCONNECTED"
	EVENT_ONLINE_USERS_LIST = "EVENT_ONLINE_USERS_LIST"
	EVENT_USER_REPLY        = "EVENT_USER_REPLY"
)
